### ISSUE TITLE
Support linux

### ISSUE THREAD

**Issue by underthestars-zhy** [leif-ibsen/SwiftECC#20]
Support linux

**Comment by johnothwolo** [comment]
@leif-ibsen any chance you can migrate to SwiftCrypto?

**Comment by leif-ibsen** [comment]
As I understand it, SwiftCrypto implements part of Apple's CryptoKit framework for use on Linux platforms.

I made an experiment letting SwiftECC depend on SwiftCrypto instead of using CryptoKit
with a dependency like

.package(url: "https://github.com/apple/swift-crypto.git", "1.0.0" ..< "3.0.0"),

in Package.swift.

I ran into all sorts of Xcode problems, like not being able to build the test suite.
I don't have access to a Linux platform, so the experiment was done on macOS.

I'm not able to invest time in trying to sort this out, so for now there is no migration.

**Comment by johnothwolo** [comment]
@leif-ibsen while I got it to build on macOS (I disabled the CryptoKit stub), the tests suspiciously took a long time. I haven't ran the original SwiftECC tests, so I don't know the expected time. 

Fortunately I have a backup Linux machine I can also test it out on. I'll post an update once I try it out.

**Comment by leif-ibsen** [comment]
The tests do take long time - about 16 minutes on my iMac

**Comment by leif-ibsen** [comment]
I did manage to get SwiftECC to work with Swift Crypto instead of CryptoKit.
The tests still took about 16 minutes.

SwiftECC won't run on Linux unless BigInt and ASN1 also run on Linux.

BigInt issue #5 was about the Swift random number function 'SecRandomCopyBytes',
which BigInt uses, not being available on Linux.

I don't know if this is still an issue, and I have no way of finding out,
since I don't have access to a Linux system.

**Comment by leif-ibsen** [comment]
With the two changes from your pull request,
did you actually run the SwiftECC test suite successfully on your Linux machine?

**Comment by johnothwolo** [comment]
@leif-ibsen yeah it worked. You might need to update BigInt's version in the ASN1 repo. In fact everything will probably need to be bumped up to a new release, and the dependencies updated too.

EDIT: I forgot to add the swift-crypto dependency.

EDIT:
You might need to merge the pull requests in a specific order and update the dependency version accordingly. Starting with BigInt, ASN1, then SwiftECC. If it were up to me I'd ditch versions for branches, since there's a bit of a dependency circle.

**Comment by leif-ibsen** [comment]
There is a line in your proposed Package.swift reading

    dependencies: ["BigInt", "ASN1", .product(name: "Crypto", package: "swift-crypto", condition: .when(platforms: [.linux]))]),
            
is the condition part necessary? If it is, shouldn't it be

    dependencies: ["BigInt", "ASN1", .product(name: "Crypto", package: "swift-crypto", condition: .when(platforms: [.macOS, .iOS, .watchOS, .linux]))]),
    
else it won't work on macOS, iOS, and watchOS. I'm a wrong?

**Comment by johnothwolo** [comment]
Right, I omitted Apple platform to remove the overhead of building Swift-Crypo, but I could modify it if you'd like.

To be honest I'm not sure if SPM builds everything then links conditionally, or if it builds what's being asked for in the dependencies.

Omitting it would work because we only need swift-crypto for CryptoKit/SecureRandom abilities. Both exist on Apple platforms but not on others.

Like I said, I was aiming for best case. Any will do, just let me know.

**Comment by leif-ibsen** [comment]
I'm having second thoughts about using Swift Crypto instead of CryptoKit
to make SwiftECC available on Linux.

The reason is that I have no experience with Linux whatsoever and no access to a Linux system,
nor the time to learn about Linux.

I wouldn't be able to answer future questions about Linux or
evaluate future bug reports regarding Linux, let alone fix them.

That's a position I don't want to be in, therefore I will not make the change to Swift Crypto.

Anyway, thank you for your effort in this issue.
