### ISSUE TITLE
ECPublicKey constructor hidden in 3.0.0

### ISSUE THREAD

**Issue by polishcode** [leif-ibsen/SwiftECC#21]
Hi,
Why would you hide a very handy constructor for ECPublicKey: https://github.com/leif-ibsen/SwiftECC/commit/ef281d148ccaa51b7174d2435f9ae37568316540#diff-1a8c1117bd15ccee147f31e050227cdb59bc4320b33a94eee8f995c669a4aeacL29 ?
Thanks,
p

**Comment by leif-ibsen** [comment]
It doesn't make sense to create a new public key by selecting a random curve point,
because you could never find the corresponding private key.

If you used the constructor

    ECPublicKey(domain:w:)

which is now not public, surely w was computed by multiplying the generator point by the private key.
So, instead use the constructor

    ECPublicKey(privateKey:)

which does just that.

**Comment by leif-ibsen** [comment]
I realize now that it could actually make sense for a party to create a public key from a curve point,
because the party received the curve point from some other party who created it from the private key
and the domain was understood.

Sorry for that, the constructor will become public again asap (possible a couple of days).

**Comment by polishcode** [comment]
Indeed. There are plenty of scenarios out there. In your second comment you are absolutely right :) Thank you.

**Comment by leif-ibsen** [comment]
Fixed in release 3.1.0
