### ISSUE TITLE
nteger literal '4294967295' overflows when stored into 'Int'

### ISSUE THREAD

**Issue by xha123** [leif-ibsen/SwiftECC#27]
![image](https://user-images.githubusercontent.com/25577710/174067091-c0e18ae5-4d7b-48d5-a452-925430569c57.png)
 how to deal with this problem？

**Comment by leif-ibsen** [comment]
Your 'Int' type is a 32 bit type. As the BigInt documentation states, it must be a 64 bit type.
Please, see issues 24 and 26

**Comment by polishcode** [comment]
Also fell into this trap. What BigInt documentation says indirectly is that all that code is effectively for 64-bit platforms only.

A legitimate use case that I have now blocked is using firebase to perform XCTest unit testing:
- my test project links SwiftECC for crypto emulation of a backend service (tests only, not the core product)
- in order to build for firebase, one needs to target "Any iOS Device (arm64)"
- XCode still tries to build SwiftECC for armv7 (tried https://stackoverflow.com/a/33646645)
Result - cannot build test package -> cannot automate testing on firebase.

I think there are two problems here:
- a literal like 0xffffffff is perfectly fine 4 byte Int (32 bits); it is Xcode compiler saying that it will be treated as a negative number;
- the BigInt should (in my opinion) use explicit Int types (Int64) to ensure the library works for both 32 and 64 bits

Right now I am stuck. I can either still try to make xcode build test package for 64 bits only (not sure if that will succeed eventually) or abandon SwiftECC and migrate to some other crypto engine. None of those options is optimal. What would be your take on this @leif-ibsen ? Thanks

**Comment by leif-ibsen** [comment]
I guess it would have been possible originally to design BigInt in such a way
that it would work on both 64 bit architectures and 32 bit architectures,
if that had been a design goal at the time, which it wasn't.

The notion that integer and unsigned integer values are 64 bit values permeates the entire BigInt design,
and it is not, in my opinion, possible to change BigInt - and hence not SwiftECC - in such a way
that they would work on 32 bit architctures.

**Comment by polishcode** [comment]
Ok, thank you for clarification @leif-ibsen.
