### ISSUE TITLE
Calculate ECDH shared secret the same way as in other frameworks

### ISSUE THREAD

**Issue by kaladivo** [leif-ibsen/SwiftECC#39]
Can this library be used to calculate shared secret the same way as in Node or Java / Kotlin? 

Here is the code that generates shared secret in Kotlin: 
```kotlin
private fun computeSharedSecret(otherPublicKey: PublicKey, myPrivateKey: PrivateKey): ByteArray {
        val keyAgreement = KeyAgreement.getInstance("ECDH")
        keyAgreement.init(myPrivateKey)
        keyAgreement.doPhase(otherPublicKey, true)
        return keyAgreement.generateSecret()
    }
```

Here is the code in NodeJS
```typescript
const myPrivateKey = Buffer.from("iUfaS6XxDCOS65sGqeunCQJR4045pTA3H4cCcYqfLpg", 'base64')
const otherSidePublicKey = Buffer.from("BJPPEL/HhVR4Yv8qyKT/1A8rcRhmP8aXBKCikXeShNhjWWWKjDuKt9zco7Flt9l14uJW1lt2kCIjb8e64wDW5Sg=", 'base64')

const ecdh = crypto.createECDH('secp256k1')
ecdh.setPrivateKey(myPrivateKey)
const sharedSecret = ecdh.computeSecret(otherSidePublicKey)
```

None of these example above use messageDigest or data parameter to calculate shared secret. Is it possible to calculate shared secret this way using SwiftECC?

**Comment by leif-ibsen** [comment]
It is possible to generate a shared secret with SwiftECC.
There is an example in the documentation section 'Secret Key Agreement'.

However, you must specify the length (in bytes) of the shared secret as well as which message digest to use.
Possible values for the message digest are

   SHA1
   SHA2_224
   SHA2_256
   SHA2_384
   SHA2_512
   
As these parameters aren't present in your examples, it must be because they use some default values.
If you know these default values, use them.

In SwiftECC, there is also a 'sharedInfo' parameter in the 'keyAgreement' method,
but it may just be an empty byte array if you don't wish to use it.

**Comment by kaladivo** [comment]
The secret is not hashed in my examples. It would be great to have option to get the secret without hashing it. In my project, we later hash/stretch it with PBKDF2 which needs to be configured with salt and iteration count. 

I have opened a pull request for this feature: #40. It would be nice if this library would support getting shared secret that is compatible with other languages/libraries :).

**Comment by leif-ibsen** [comment]
SwiftECC's Secret Key Agreement actually uses the key derivation function specified in

   Standards for Efficient Cryptography 1 (SEC 1), Certicom Corp. 2009
 
section 3.6.1. That's why it needs a message digest and a shared secret length.

However, I can see your point, and I will look into implementing the Diffie-Hellman primitive
as specified in section 3.3 in the above document which I guess is what you ask for.

May take a little while to do it.

**Comment by kaladivo** [comment]
Thanks, let me know if I can help somehow :).

**Comment by leif-ibsen** [comment]
I can see from your proposed change that you wish to skip hashing during the secret key generation.

This is not in accordance with the specifications in 'SEC 1: Elliptic Curve Cryptography',
and it is not to be implemented in SwiftECC.

The value of the 'length' parameter depends on what you want to use the generated secret key for.
F.ex. if it is to be an AES128 key, then the value should be 16, which is the key size for AES128.

**Comment by leif-ibsen** [comment]
I saw your question about this issue on stackoverflow.
If you consider the function

   func computeSharedSecret(_ privKey: ECPrivateKey, _ pubKey: ECPublicKey) throws -> Bytes {
       assert(privKey.domain == pubKey.domain)
       let Z = try privKey.domain.multiplyPoint(pubKey.w, privKey.s).x.asMagnitudeBytes()
       return privKey.domain.align(Z)
   }
   
and then 

    let myPrivateKey = try base64ToPrivateKey(x: "DmuxAqe2H4Ntyuc9Vex/Zbl4+w5/sdPWBBlmJqU+pjs=")!
    let otherSidePublickey = try base64ToPublicKey(x: "BJPPEL/HhVR4Yv8qyKT/1A8rcRhmP8aXBKCikXeShNhjWWWKjDuKt9zco7Flt9l14uJW1lt2kCIjb8e64wDW5Sg=")!

		let sharedSecret = try computeSharedSecret(myPrivateKey, otherSidePublickey)
		print(sharedSecret)
		
it prints

   [253, 37, 191, 153, 91, 32, 52, 218, 151, 171, 141, 156, 234, 126, 145, 179,
    19, 199, 117, 125, 103, 38, 125, 236, 172, 242, 122, 212, 131, 117, 124, 241]

Is that what you are looking for? If it is, you can just add the 'computeSharedSecret' function to your code.
